export const CONNECT_WALLET_BEGIN = "CONNECT_WALLET_BEGIN";
export const CONNECT_WALLET_SUCCESS = "CONNECT_WALLET_SUCCESS";
export const CONNECT_WALLET_ERROR = "CONNECT_WALLET_ERROR";
export const INIT_ETH_HELPER = "INIT_ETH_HELPER";